name: Deploy
permissions:
  contents: read
on:
  push:
    tags:
      - "*"
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          tools: composer
      - name: Install production dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          ASSETS_DIR: wpassets
          SLUG: nginx-helper
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
